### PR TITLE
Create TraderSlots.cs

### PR DESCRIPTION
**Pull request by Enjoyop**

### CODE REVIEW

**Comment by Incr3dible** [comment]
has this encoding been checked?
Please provide a description in future pull requests.

**Comment by Enjoyop** [comment]
Yeah.

How much do you plan to develop this project?

Allow me to add csv files I am enum in order of gloabal_id.
or you add.

Also level npcs.json files are old.

**Comment by Incr3dible** [comment]
"How much do you plan to develop this project?"
I don't know, as long as it's fun.

"Also level npcs.json files are old."
Soon

**Comment by Enjoyop** [comment]
Can UCS client be run with cerberus v3 ?

**Comment by Incr3dible** [comment]
No

**Comment by Enjoyop** [comment]
Will the CoC client open?
Of course I know that there will be errors due to csv / Logic.

There are many shortcomings in your project and you can add a few things from cerberus v3.

For example, I think the BuyBuilding command is very different and bad.

I really want something good quality.

**Comment by Incr3dible** [comment]
"I really want something good quality."
Well... it's free

**Comment by Enjoyop** [comment]
what ?

**Comment by jakovmarkovanovic** [comment]
Yea free sorce for New version coc difredn coomads and full is rc4 is this

**Comment by Incr3dible** [comment]
what

**Pull request closed without merging**
